version: '3'

services:
    modelval:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        volumes:
            - static:/modelvalidation/static
volumes:
  static:
